name: Build site on schedule or main branch update

on:
  push:
    branches:
      - main
  schedule:
    # 表达式生成  https://crontab.guru/
    # 此处是UTC时间 即北京时间 -8小时
    # 每半小时执行一次
    - cron: "0,30 0-23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm i
      - name: Build the feed
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
